module Tatami
  module Constants
    module HeaderNames
      ROOT = 'Root'
      ARRANGE = 'Arrange'
      ASSERTION = 'Assertion'
      HTTP_REQUEST_EXPECTED = 'HttpRequest Expected'
      HTTP_REQUEST_ACTUAL = 'HttpRequest Actual'
      URI = 'Uri'
      STATUS_CODE = 'StatusCode'
      HEADERS = 'Headers'
      COOKIES = 'Cookies'
      XSD = 'Xsd'
      CONTENTS = 'Contents'
      BASE_URI = 'BaseUri'
      METHOD = 'Method'
      USER_AGENT = 'UserAgent'
      PATH_INFOS = 'PathInfos'
      QUERY_STRINGS = 'QueryStrings'
      FRAGMENT = 'Fragment'
      CONTENT = 'Content'
      NAME = 'Name'
      IS_LIST = 'IsList'
      IS_DATE_TIME = 'IsDateTime'
      IS_TIME = 'IsTime'
      EXPECTED = 'Expected'
      ACTUAL = 'Actual'
      KEY = 'Key'
      VALUE = 'Value'
      QUERY = 'Query'
      ATTRIBUTE = 'Attribute'
      EXISTS = 'Exists'
      PATTERN = 'Pattern'
      FORMAT = 'Format'
      FORMAT_CULTURE = 'FormatCulture'
      URL_DECODE = 'UrlDecode'
    end
  end
end